export const menu = [
  {
    id: 0,
    name: "Honey BBQ Wings",
    searchName: "honey bbq wings",
    menuSection: "appetizers",
    price: 150.00,
  },
  {
    id: 1,
    name: "Sweet & Spicy Mini Meatballs",
    searchName: "sweet & spicy mini meatballs",
    menuSection: "appetizers",
    price: 150.00,
  },
  {
    id: 2,
    name: "Fish Sliders with Chipotle Aioli",
    searchName: "fish sliders with chipotle aioli",
    menuSection: "appetizers",
    price: 150.00,
  },
  {
    id: 3,
    name: "Quinoa with Avocado & Roasted Corn",
    searchName: "quinoa with avocado & roasted corn",
    menuSection: "appetizers",   
    price: 150.00,
  },
  {
    id: 4,
    name: "Smoked Salmon Crostini",
    searchName: "smoked salmon crostini",
    menuSection: "appetizers",
    price: 150.00,
  },
  {
    id: 5,
    name: "Kale Salad with Caesar Dressing & Grilled Shrimp",
    searchName: "kale salad with caesar dressing & grilled shrimp",
    menuSection: "salads",
    price: 150.00,
  },
  {
    id: 6,
    name: "Arugula Salad with Honey Mustard Vinaigrette & Toasted Nuts",
    searchName: "arugula salad with honey mustard vinaigrette & toasted nuts",
    menuSection: "salads",
    price: 150.00,
  },
  {
    id: 7,
    name: "Spring Mix with Sweet & Spicy Steamed Salmon, Avocado Fans and Champagne Vinagrette",
    searchName: "spring mix with sweet & spicy steamed salmon avocado fans and champagne vinagrette",
    menuSection: "salads",
    price: 150.00,
  },
  {
    id: 8,
    name: "Caprese Avocado Cups with Tomatoes & Watermelon drizzled in Balsamic Vinaigrette",
    searchName: "caprese avocado cups with tomatoes & watermelon drizzled in balsamic vinaigrette",
    menuSection: "salads",
    price: 150.00,
  },
  {
    id: 9,
    name: "Garlic Herb Lamb Chop with Fingerling Potatoes and Honey Roasted Carrots",
    searchName: "garlic herb lamb chop with fingerling potatoes and honey roasted carrots",
    menuSection: "dinners",
    price: 150.00,
  },
  {
    id: 10,
    name: "Seared Ribeye Steak with Balsalmic Onions, Roasted Brussels Sprouts and Broccoli",
    searchName: "seared ribeye steak with balsalmic onions, roasted brussels sprouts and broccoli",
    menuSection: "dinners",
    price: 150.00,
  },
  {
    id: 11,
    name: "Escovitch Snapper with Garlic Red Mashed Potatoes & Gravy and Fiesta Corn Salad",
    searchName: "escovitch snapper with garlic red mashed potatoes & gravy and fiesta corn salad",
    menuSection: "dinners",
    price: 150.00,
  },
  {
    id: 12,
    name: "Roasted Herb Garlic Chicken with White Rice & Beans and Sweet Plantains Strips",
    searchName: "roasted herb garlic chicken with white rice & beans and sweet plantains strips",
    menuSection: "dinners",
    price: 150.00,
  },
  {
    id: 13,
    name: "Sausage & Shrimp Alfredo with Mixed Vegetables and Garlic Toast",
    searchName: "sausage & shrimp alfredo with mixed vegetables and garlic toast",
    menuSection: "dinners",
    price: 150.00,
  }
];
